name: Deploy Next.js to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies & Build Next.js
      run: |
        cd my-app
        npm install --legacy-peer-deps
        npm run build

    - name: Upload build to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        source: "my-app/*"
        target: "/home/ubuntu/nextjs-app"
        strip_components: 1

    - name: Restart PM2 on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/nextjs-app
          npm install --legacy-peer-deps
          pm2 stop nextapp || true
          pm2 start npm --name nextapp -- start
          pm2 save
