name: Deploy Next.js to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code (Force correct path)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
          path: var_repo

      - name: Install dependencies
        run: |
          cd var_repo
          npm install

      - name: Build Next.js
        run: |
          cd var_repo
          npm run build
